name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload "@argos-ci/cli" dist
        uses: actions/upload-artifact@v3
        with:
          name: cli-dist
          path: packages/cli/dist

      - name: Upload "@argos-ci/core" dist
        uses: actions/upload-artifact@v3
        with:
          name: core-dist
          path: packages/core/dist

  unit:
    needs: ["build"]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Download "@argos-ci/cli" dist
        uses: actions/download-artifact@v3
        with:
          name: cli-dist
          path: packages/cli/dist

      - name: Download "@argos-ci/core" dist
        uses: actions/download-artifact@v3
        with:
          name: core-dist
          path: packages/core/dist

      - name: Test
        run: npm run test

  e2e:
    needs: ["build"]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Download "@argos-ci/cli" dist
        uses: actions/download-artifact@v3
        with:
          name: cli-dist
          path: packages/cli/dist

      - name: Download "@argos-ci/core" dist
        uses: actions/download-artifact@v3
        with:
          name: core-dist
          path: packages/core/dist

      - name: Run integration tests
        run: npm run e2e
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          NODE_VERSION: ${{ matrix.node-version }}
          OS: ${{ matrix.os }}
