name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  unit:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install last npm version
        if: ${{ matrix.node-version == 14 }}
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  e2e:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install last npm version
        if: ${{ matrix.node-version == 14 }}
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - run: cat packages/core/dist/index.mjs

      - name: Run integration tests
        run: npm run e2e
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          NODE_VERSION: ${{ matrix.node-version }}
